export const FailureReasonCode = Object.freeze({
  MISSING_AUTHORITY_LINKAGE: 'MISSING_AUTHORITY_LINKAGE',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  UNKNOWN_REQUEST: 'UNKNOWN_REQUEST',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  DECRYPT_NOT_AUTHORIZED: 'DECRYPT_NOT_AUTHORIZED',
  POLICY_MISMATCH: 'POLICY_MISMATCH',
  RISK_MISMATCH: 'RISK_MISMATCH',
  ATTESTATION_INVALID: 'ATTESTATION_INVALID'
});

export const REQUIRED_AUTHORITY_FIELDS = Object.freeze([
  'intentId',
  'mandateId',
  'policyVersion',
  'policyHash',
  'riskAssessmentId',
  'authorizationId',
  'correlationId'
]);

export const ExecutionStatus = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  EXECUTED: 'EXECUTED',
  VERIFIED: 'VERIFIED',
  VERIFY_REJECTED: 'VERIFY_REJECTED',
  DECRYPT_AUTHORIZED: 'DECRYPT_AUTHORIZED',
  DECRYPT_DENIED: 'DECRYPT_DENIED',
  DECRYPTED: 'DECRYPTED'
});
